services:
  front:
    image: ${DOCKER_IMAGE}
    container_name: ${DOCKER_CONTAINER}
    restart: unless-stopped
    environment:
      DEV: "false"
      HOST: "127.0.0.1"
      API_URL: "https://127.0.0.1/api"
      DATA_URL: "https://127.0.0.1/data"
    ports:
      - "127.0.0.1:${DOCKER_PORT}:80"
    volumes:
      - ${DOCKER_MOUNTED}:/mounted
